services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: webhook_user
      POSTGRES_PASSWORD: webhook_pass
      POSTGRES_DB: webhooks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webhook_user -d webhooks"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  pgdata:
